python9_django/web/home/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    # 首页
    url(r'^$', views.index,name='index' ),
    # 登录
    url(r'^login/$', views.login,name='login' ),
    # 执行登录
    url(r'^dologin/$', views.dologin,name='dologin' ),
    # 注册
    url(r'^register/$', views.register,name='register' ),
    # 执行注册
    url(r'^doregister/$', views.doregister,name='doregister' ),
    # 退出登录
    url(r'^outlogin/$', views.outlogin,name='outlogin' ),
    

    # 列表页
    url(r'^list/(?P<tid>[0-9]+)$', views.list,name='list' ),
    # 购买页
    url(r'^info/(?P<gid>[0-9]+)$', views.info,name='info' ),
    # 加入购物车
    url(r'^cart/add/$',views.cartadd,name='cartadd'),
    # 购物车列表
    url(r'^cart/list/$',views.cartlist,name='cartlist'),
    # 清空购物车
    url(r'^cart/clear/$',views.cartclear,name='cartclear'),
    # 商品删除
    url(r'^cart/del/(?P<sid>[0-9]+)$',views.delete,name='shanchu'),
    # 商品数量加减
    url(r'^cart/edit/$',views.cartedit,name='cartedit'),


    # 下单
    # 订单确认
    url(r'^order/confirm/$',views.orderconfirm,name='orderconfirm'),
    # 生成订单
    url(r'^order/create/$',views.ordercreate,name='ordercreate'),
    # 付款
    url(r'^order/buy/$',views.orderbuy,name='orderbuy'),
    # 我的订单
    url(r'^myorder/$',views.myorder,name='myorder'),
    # 个人中心 地址管理
    url(r'^myxin/$',views.myxin,name='myxin'),
    # 修改地址
    url(r'^addressedit/(?P<aid>[0-9]+)$',views.addressedit,name='addressedit'),
    # 执行修改
    url(r'^addressupdate/$',views.addressupdate,name='addressupdate'),
    # 地址删除
    url(r'^adsressdel/(?P<bid>[0-9]+)$',views.adsressdel,name='adsressdel'),









]

python9_django/web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^ueditor/', include('ueditor.urls')),
    url(r'^admin/', include('myadmin.urls')),
    url(r'^', include('home.urls')),

]

python9_django/web/home/models.py
from django.db import models

# Create your models here.

python9_django/web/myadmin/models.py
from django.db import models

# Create your models here.

# 会员管理
class Users(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=77)
    email = models.CharField(max_length=100,null=True)
    phone = models.CharField(max_length=11,null=True)
    sex = models.CharField(max_length=1,null=True)
    age = models.IntegerField(null=True)
    picurl = models.CharField(max_length=100,default='/static/pics/default/default.jpg',null=True)
    # 0 正常 1 禁用 
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)


# 商品分类管理
class Types(models.Model):
    name = models.CharField(max_length=50)
    pid = models.IntegerField()
    path = models.CharField(max_length=20)


# 商品模型
class Goods(models.Model):
    # 商品所属分类
    typeid = models.ForeignKey(to="Types", to_field="id")
    # 商品标题
    title = models.CharField(max_length=255)
    # 商品价格
    price = models.DecimalField(max_digits=8, decimal_places=2)
    # 商品库存
    storage = models.IntegerField()
    # 商品图片
    pic = models.CharField(max_length=50)
    # 商品详情
    info = models.TextField()
    # 购买数量
    num  =  models.IntegerField(default=0)
    # 点击次数
    clicknum =  models.IntegerField(default=0)
    # 商品状态 1：新品、2：热销、3：下架
    status = models.IntegerField(default=1)
    # 商品添加时间
    addtime = models.DateTimeField(auto_now_add=True)



# 会员收货地址 模型

class Address(models.Model):
    # 用户id
    uid = models.ForeignKey(to="Users", to_field="id")
    # 收货人
    aname = models.CharField(max_length=20)
    # 收货地址
    aads = models.CharField(max_length=255)
    # 收货电话
    aphone = models.CharField(max_length=11)
    # 是否为默认 1 默认,
    status = models.IntegerField(default=0)



# 订单表
class Order(models.Model):
    uid = models.ForeignKey('Users',to_field="id")
    address = models.ForeignKey('Address',to_field='id')
    totalprice = models.FloatField()
    totalnum = models.IntegerField()
    # 1 未付款 2已付款,待发货,3已发货,待收货,4已完成,5已取消
    status = models.IntegerField()
    addtime = models.DateTimeField(auto_now_add=True)

# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey('Order',to_field="id")
    gid =  models.ForeignKey('Goods',to_field="id")
    num = models.IntegerField()
    price = models.FloatField()

python9_django/web/home/views.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,JsonResponse
from myadmin.models import Users,Types,Goods,Address,Order,OrderInfo
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.sessions.models import Session 

# Create your views here.

def erji():
    # 获取所有顶级分类
    data = Types.objects.filter(pid = 0)
    return data

# 首页
def index(request):

    # 获取顶级分类
    data = Types.objects.filter(pid = 0)
    for x in data:
        x.sub = Types.objects.filter(pid = x.id)
        for y in x.sub:
            y.sub = Goods.objects.filter(typeid=y.id)[:4]


    context = {'typelist':erji(),'ilist':data}

    return render(request,'home/index.html',context)
# 列表页
def list(request,tid):

    # 根据id获取当前分类的信息
    tod = Types.objects.get(id=tid)
    if tod.pid == 0:
        # 顶级分类
        data = tod
        # 获取子类 [{},{}]
        data.sub = Types.objects.filter(pid=tod.id)
        ids = []
        for x in data.sub:
            ids.append(x.id)
        
        data.goods = Goods.objects.filter(typeid__in=ids)

        # {'name':'服装','sub':[{'name':'男装'},{'name':'女装'}],'goods':[{},{},{},{}]}

    else:
        # {'name':'服装','sub':[{'name':'男装'},{'name':'女装'}],'goods':[{},{}],'obj':{'name':'男装'}}
        
        # 先获取父级对象
        data = Types.objects.get(id=tod.pid)
        # 获取当前子类的商品信息
        data.goods = Goods.objects.filter(typeid=tod.id)
        # 获取所有的同级信息,包括当前类
        data.sub = Types.objects.filter(pid=tod.pid)
        # 给data数据追加了一个obj对象
        data.obj = tod



    context = {'typelist':erji(),'data':data}
    return render(request,'home/list.html',context)

# 加入购物车
def cartadd(request):
    try:
        # 接收商品id
        gid = request.GET['gid']
        # 加入购物车的数量
        num = int(request.GET['num'])
        print(num)
        print(gid)

        # 获取购物车数据
        data = request.session.get('cart',{})
        
        # 判断商品是否已经存在与购物车中
        # {1:{},2:{}}
        if gid in data:
            # 如果已经存在,找到商品,修改数量
            data[gid]['num'] += num
        else:
            # 获取商品信息
            goods = Goods.objects.get(id=gid)
            # 把新的商品信息,追加到data数据中
            data[gid] = {'id':goods.id,'title':goods.title,'price':str(goods.price),'pic':goods.pic,'num':num}


        # 加入到session {1:{},2:{}}
        request.session['cart'] = data


        return JsonResponse({'code':0,'msg':'加入购物车成功'})
    except:
        return JsonResponse({'code':1,'msg':'加入购物车失败'})

# 购物车列表
def cartlist(request):


    context = {'typelist':erji()}
    return render(request,'home/cartlist.html',context)

# 清空购物车
def cartclear(request):

    request.session['cart'] = {}

    return HttpResponse('<script>location.href="/cart/list/"</script>')

# 商品数量加减
def cartedit(request):
    gid = request.GET.get('gid')
    num = int(request.GET.get('num'))

    # 读取购物车中的商品

    data = request.session['cart']

    # 修改商品数量
    data[gid]['num'] = num

    # 把数据加载到session中
    request.session['cart'] = data

    return HttpResponse('')

# 确认订单
def orderconfirm(request):

    

    if request.method == 'GET':

        # 获取用户选择的商品
        ids = request.GET['ids'].split(',')
        
        # 从session中读取购物车信息
        cartdata = request.session['cart']
        orderdata = {}

        for x in cartdata:
            if x in ids:
                orderdata[x] = cartdata[x]

        # 把用户选择购买的商品存入session
        request.session['order'] = orderdata

        # 需要让用户确认收货地址 获取当前用户的所有地址信息
        address = Address.objects.filter(uid=request.session['VipUser']['uid'])

        context = {'typelist':erji(),'address':address}
        return render(request,'home/orderconfirm.html',context)

    elif request.method == 'POST':

        # 执行地址的添加
        ob = Address()
        ob.uid = Users.objects.get(id=request.session['VipUser']['uid'])
        ob.aname = request.POST['aname']
        ob.aphone = request.POST['aphone']
        ob.aads = request.POST['aads']

        # 状态修改
        s = request.POST.get('status',0)
        # 判断当前如果设置为默认值,
        if s == '1':
            # 把其它的地址修改状态 0 
            obs = Address.objects.filter(id = request.session['VipUser']['uid']).filter(status=1)
            for x in obs:
                x.status = 0
                x.save()

        ob.status = s
        ob.save()
        return HttpResponse('<script>alert("地址添加成功");location.href="/order/confirm/?ids='+request.GET['ids']+'"</script>')

# 生成订单
def ordercreate(request):
    # 在session中获取商品数据
    data = request.session['order']

    totalprice = 0
    totalnum = 0

    for x in data:
        
        n = float(data[x]['price']) * data[x]['num']

        totalprice += n
        totalnum += data[x]['num']
    # 创建订单
    order = Order()
    order.uid = Users.objects.get(id = request.session['VipUser']['uid'])
    order.address = Address.objects.get(id=request.POST['addressid'])
    order.totalprice = totalprice
    order.totalnum = totalnum
    order.status = 1
    order.save()

    # 先读取购物车里面的数据
    cart = request.session['cart']

    # 创建订单详情
    for x in data:
        orderinfo = OrderInfo()
        orderinfo.orderid = order
        goods = Goods.objects.get(id = x)
        orderinfo.gid = goods
        orderinfo.num = data[x]['num']
        orderinfo.price = data[x]['price']
        orderinfo.save()
        # 将购物车中的商品删除
        del cart[x]

        # 修改狗台数据
        goods.num += data[x]['num']
        goods.storage -= data[x]['num']
        goods.save()

    # 清空session中的订单数据
    request.session['order'] = {}
    # 更新购物车
    request.session['cart'] = cart


    # 跳转到付款页面
    return HttpResponse('<script>alert("订单创建成功,请立即支付");location.href="/order/buy/?orderid='+str(order.id)+'"</script>')

# 付款
def orderbuy(request):
    
    orderid = request.GET.get('orderid',None)
    if orderid:
        # 通过订单id获取订单信息,并展示
        order = Order.objects.get(id=orderid)

        times='<a href="'+reverse('index')+'">手动跳转</a>'
        dataend='秒后将自动跳转'
        context = {'typelist':erji(),'order':order,'d':dataend,'t':times}
        return render(request,'home/fukuan.html',context)

# 详情页
def info(request,gid):
    
    # 根据id获取商品的信息
    ginfo = Goods.objects.get(id=gid)

    context = {'typelist':erji(),'ginfo':ginfo}
    return render(request,'home/buy.html',context) 

# 登录页
def login(request):

    return render(request,'home/login.html')

# 退出登录
def outlogin(request):
    del request.session['VipUser']
    return HttpResponse('<script>alert("已退出登录");location.href="/"</script>')
    
# 执行登录
def dologin(request):
    # 判断验证码是否正确
    if request.POST['code'].lower() != request.session['verifycode'].lower():
        return HttpResponse('<script>alert("验证码错误");location.href="/login/"</script>')
    # 判断用户是否存在
    ob = Users.objects.filter(username = request.POST['username'])
    if ob:
        ob = ob[0]
        # 判断密码是否正确
        if check_password(request.POST['password'],ob.password):
            request.session['VipUser'] = {'name':ob.username,'pic':ob.picurl,'uid':ob.id}

            return HttpResponse('<script>alert("登陆成功");location.href="/"</script>')

    return HttpResponse('<script>alert("用户或者密码不存在");location.href="/login/"</script>')

# 注册页
def register(request):

    return render(request,'home/register.html')

# 执行注册页
def doregister(request):
    aa = request.POST['username']
    bb = request.POST['password']
    if not aa:
        return HttpResponse('<script>alert("请输入用户名");location.href="/register/"</script>')
    if not bb:
        return HttpResponse('<script>alert("请输入密码");location.href="/register/"</script>')

    else:
        # 判断用户名是否存在
        res = Users.objects.filter(username=request.POST['username']).exists()

        if res:
            return HttpResponse('<script>alert("用户名已经存在");location.href="/register/"</script>')
        else:
            ob = Users()
            ob.username = request.POST['username']
            ob.password = make_password(request.POST['password'], None, 'pbkdf2_sha256')
            ob.save()

            request.session['VipUser'] = {'name':ob.username,'pic':ob.picurl,'uid':ob.id}

            return HttpResponse('<script>alert("注册成功");location.href="/"</script>')

# 购物车删除
def delete(request,sid):

    aa = request.session['cart']

    del aa[sid]

    request.session['cart'] = aa

    return HttpResponse('<script>location.href="/cart/list/"</script>')
    
# 我的订单
def myorder(request):
    # 查询所有信息
    orders = Order.objects.filter(uid=request.session['VipUser']['uid'])
    # 分配数据
    context = {'typelist':erji(),'orders':orders}
    return render(request,'home/myorder.html',context)

# 地址管理
def myxin(request):
    address = Address.objects.filter(uid=request.session['VipUser']['uid'])
    print(address)
    # 分配数据
    context = {'typelist':erji(),'address':address}

    return render(request,'home/zhongxin.html',context)

# 修改地址
def addressedit(request,aid):
    # 获取地址数据
    ad = Address.objects.get(id = aid)

    # 分配数据
    context = {'tyoelist':erji(),'adlist':ad}
    return render(request,'home/addressedie.html',context)

# 执行修改
def addressupdate(request):
    
    ad = Address.objects.get(id = request.POST['id'])
    ad.aname = request.POST.get('aname')


    ad.aads = request.POST.get('aads')
    ad.aphone = request.POST.get('aphone')
    ad.save()
    return HttpResponse('<script>alert("修改成功");location.href="/myxin/"</script>')

# 地址删除
def adsressdel(request,bid):
    
    ad = Address.objects.get(id = bid)

    ad.delete()

    return HttpResponse('<script>alert("删除成功");location.href="/myxin/"</script>')

python9_django/web/templates/home/addressedie.html
{% extends 'home/public/base.html' %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/home/css/order.css">
<link rel="stylesheet" type="text/css" href="/static/home/css/order-app.css">


{% endblock %}

{% block con %}

<div class="mainbody order">
        <div class="container">
            <!-- 面包屑导航 -->
            <div class="crumbs col-xs-12 col-sm-12">
                <ol class="breadcrumb">
                    <li class="hidden-xs hidden-sm"><a href="index.html">首页</a></li>
                    <li class="hidden-xs hidden-sm"><a href="member.html">我的商城</a></li>
                    <li class="active">个人中心</li>
                </ol>
            </div><!-- 面包屑导航 E-->
            
            <div class="main clearfix">
                <!-- 左侧导航 -->
                <div class="left-nav f-fl col-md-4 hidden-xs hidden-sm">
                    <div class="nav-main">
                        <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>订单中心</a>
                        <a href="{% url 'myorder' %}" class="ml">我的订单</a>
                        <a href="" class="ml ">我的回购单</a>
                        <a href="" class="ml ">我的意外保</a>
                        <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>个人中心</a>
                        <a href="" class="ml active">地址管理</a>
                        <a href="" class="ml ">我的收藏</a>
                        <a href="" class="ml ">消息提醒</a>
                        <a href="" class="ml ">建议反馈</a>
                    </div>
                </div><!-- 左侧导航 E-->
                <!-- 右侧内容展示 -->
                <div class="right-content f-fr col-md-8 col-xs-12 col-sm-12">
                    <div class="order-main">
                        <form action="{% url 'addressupdate' %}" method="post" enctype="multipart/form-data" class="am-form tpl-form-border-form tpl-form-border-br">
                            <div class="am-form-group">
                                <label for="user-name" class=" am-form-label">收货人: </label>
                                <div class="am-u-sm-9">
                                    <input type="text" name = 'aname' value = '{{ adlist.aname }}' class="tpl-form-input" id="user-name" placeholder="请输入收货人姓名">
                                </div>
                            </div>
                            <br>
                            <div class="am-form-group">
                                <label for="user-name" class="am-u-sm-3 am-form-label">收货地址: </label>
                                <div class="am-u-sm-9">
                                    <input type="text" name = 'aads' value = '{{ adlist.aads }}' class="tpl-form-input" id="user-name" placeholder="请输入收货地址">
                                </div>
                            </div>
                            <br>
                            <div class="am-form-group">
                                <label for="user-name" class="am-u-sm-3 am-form-label">电话: </label>
                                <div class="am-u-sm-9">
                                    <input type="text" name = 'aphone' value = '{{ adlist.aphone }}' class="tpl-form-input" id="user-name" placeholder="请输入电话">
                                </div>
                            </div>
                            <br>
                            <br>
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ adlist.id }}">
                            <div class="am-form-group">
                                <div class="am-u-sm-9 am-u-sm-push-3">
                                <button class="col-md-2  mz-btn btn-danger btn-lg">修改</button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>  
    </div>


{% endblock %}

python9_django/web/templates/home/fukuan.html
{% extends 'home/public/base.html' %}


{% block mbx %}
<div class="navbar-left">
    <ol class="breadcrumb">
        <li >购物车</li>
        <li >确认订单</li>
        <li class="active">在线支付</li>
        <li>完成 </li>
    </ol>
</div>

{% endblock %}

{% block con %}
<center>
<br><br><br><br><br>
<div class="mainbody cart">
    <div class="container">
    
        <h3>请为你的订单支付:</h3><br>
        <p>订单号:51090244361541573081{{ order.id }}</p>
        <p>订单总价:{{ order.totalprice }}元</p>
        <br>
        <br>
        <p id="p1">跳转</p>
    </div>
</div>
    <div class="cart-footer" id="cartFooter">
        <div class="container">
           <div class="cart-footer-left col-md-2 col-md-offset-9">
               
               <!-- <span class="cart-remove-selected" id="removeSelected">删除选中的商品</span> -->
                <form id="createFrom" action="" method="post" style="display: inline-block;">
                    {% csrf_token %}
                    <input type="hidden" name="addressid" value="">
                    <button class="mz-btn btn-danger btn-lg  " id="cartSubmit">立即付款</button>
                </form>  

            </div>
        </div>
    </div>
</center>
<script>
var start=5;
var stop=-1;
function f() {
    var a=start+'{{ d }}'+'{{ t|safe }}';
    res=document.getElementById('p1').innerHTML=a;
    start+=stop;
    if(start<=0){
        location.href="{% url 'index' %}";
    }
     setTimeout(f,1000)
}
window.onload=f;




</script>


{% endblock %}

python9_django/web/templates/home/myorder.html
{% extends 'home/public/base.html' %}

{% block css %}
<link rel="stylesheet" type="text/css" href="/static/home/css/order.css">
<link rel="stylesheet" type="text/css" href="/static/home/css/order-app.css">


{% endblock %}

{% block con %}

<div class="mainbody order">
        <div class="container">
            <!-- 面包屑导航 -->
            <div class="crumbs col-xs-12 col-sm-12">
                <ol class="breadcrumb">
                    <li class="hidden-xs hidden-sm"><a href="index.html">首页</a></li>
                    <li class="hidden-xs hidden-sm"><a href="member.html">我的商城</a></li>
                    <li class="active">我的订单</li>
                </ol>
            </div><!-- 面包屑导航 E-->
            
            <div class="main clearfix">
                <!-- 左侧导航 -->
                <div class="left-nav f-fl col-md-4 hidden-xs hidden-sm">
                    <div class="nav-main">
                        <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>订单中心</a>
                        <a href="{% url 'myorder' %}" class="ml active">我的订单</a>
                        <a href="" class="ml ">我的回购单</a>
                        <a href="" class="ml ">我的意外保</a>
                        <a href="javascript:;" class="type-title"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>个人中心</a>
                        <a href="{% url 'myxin' %}" class="ml ">地址管理</a>
                        <a href="" class="ml ">我的收藏</a>
                        <a href="" class="ml ">消息提醒</a>
                        <a href="" class="ml ">建议反馈</a>
                    </div>
                </div><!-- 左侧导航 E-->
                <!-- 右侧内容展示 -->
                <div class="right-content f-fr col-md-8 col-xs-12 col-sm-12">
                    <div class="order-main">
                        <div class="type-tab-btn">
                            <a href="javascript:;" class="allOrder active col-20" data-type="-1">全部订单</a><i class="line hidden-xs hidden-sm">|</i>
                            <a class="waitPay col-20" href="javascript:;" data-type="0">待付款<span class="amount _actAmount"></span></a><i class="line hidden-xs hidden-sm">|</i>
                            <a class="waitDeliver col-20" href="javascript:;" data-type="1">待发货</a><i class="line hidden-xs hidden-sm">|</i>
                            <a class="hasDeliver col-20" href="javascript:;" data-type="2">已发货</a><i class="line hidden-xs hidden-sm">|</i>
                            <a class="other col-20" href="javascript:;" data-type="99">其他</a>
                        </div>
                        <div class="list-head hidden-xs hidden-sm">
                        <ul class="clearfix">
                            <li class="w50">
                                <select id="checkType" class="check-type">
                                    <option value="0">近三个月的订单</option>
                                    <option value="1">全部订单</option>
                                </select>
                                订单明细
                            </li>
                            <li class="w125">售后</li>
                            <li class="w125">金额</li>
                            <li class="w125">状态</li>
                            <li class="w125">操作</li>
                        </ul>
                        </div>

                        <div id="tableList" class="type-contain ui-load-container">
                            <div class="ui-load-content"><input id="unPayNum" value="0" type="hidden">
                                <table class="orderItem">
                                    <tbody>
                                        {% for v in orders %}
                                            <tr class="trHead hidden-xs hidden-sm">
                                                <td colspan="4" class="title clearfix">
                                                  <div class="f-fl">
                                                    下单时间：<span class="time">{{ v.addtime|date:'Y-m-d H:i:s'}}</span>
                                                    订单号：<span class="orderNumber">51090244361541573081{{ v.id }}</span>
                                                  </div>
                                                </td>
                                            </tr>
                                            <tr class="list-box b-l b-r b-b">
                                                <td class="list b-r j-iamCart">
                                                    <div class="cart-wrap j-CartWrap">
                                                        <div class="shop j-shop j-amLight">
                                                            {% for vv in v.orderinfo_set.all %}
                                                            <div class="item b-t clearfix j-item j-iamMain">
                                                                <a class="productDetail nameWidth col-xs-4 col-sm-4" href="#" target="_blank">
                                                                    <img src="{{ vv.gid.pic }}" class="f-fl">
                                                                </a>
                                                                <div class="describe f-fl col-xs-8 col-sm-8">
                                                                    <div class="vertic clearfix">
                                                                        <span class="clearfix">
                                                                            <a class="productDetail nameWidth" href="#" target="_blank">
                                                                            <i>{{ vv.gid.title }}</i> </a>
                                                                            <p>
                                                                            ￥{{ vv.price }}×{{ vv.num }}
                                                                            </p>
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            {% endfor %}

                                                        </div>
                                                    </div>
                                                </td>

                                                <td class="b-r w125 center price b-t hidden-xs hidden-sm">
                                                    <div class="priceDiv">
                                                        ￥ {{ v.totalprice }}
                                                        
                                                    </div>
                                                </td>
                                                <td class="b-r w125 center state b-t hidden-xs hidden-sm">
                                                    <div class="stateDiv">
                                                        {% if v.status == 1 %}
                                                           <div>未付款<br></div>
                                                        {% elif v.status == 2%}
                                                           <div>待发货<br></div>
                                                        {% elif v.status == 3%}
                                                           <div>待收货<br></div>
                                                        {% elif v.status == 4%}
                                                           <div>待评价<br></div>
                                                        {% elif v.status == 5%}
                                                           <div>已取消<br></div>
                                                        {% endif %}
                                                          
                                                    </div>
                                                </td>
                                                <td class="w125 center opreat b-t hidden-xs hidden-sm">
                                                    <ul>
                                                        <li class="more"><a href="#" target="_blank">查看详情</a></li>
                                                    </ul>
                                                </td>
                                            </tr>

                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>


{% endblock %}